// <auto-generated />
using Fundos_Imboliarios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fundos_Imboliarios.Migrations.Fundo_Imobiliario
{
    [DbContext(typeof(Fundo_ImobiliarioContext))]
    partial class Fundo_ImobiliarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Fundos_Imboliarios.Model.Fundos_Imboliario", b =>
                {
                    b.Property<int>("Codigo_Fundos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adm_Fundos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Desp_Adm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Dividendo")
                        .HasColumnType("float");

                    b.Property<int>("Id_carteira")
                        .HasColumnType("int");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo_Fundos");

                    b.ToTable("Fundos_Imobiliarios");
                });
#pragma warning restore 612, 618
        }
    }
}
